### ISSUE TITLE
iranian mirror would be great

### ISSUE THREAD

**Issue by killajoe** [endeavouros-team/mirrors#7]
https://mirror.bardia.tech/endeavouros/

https://bardia.tech/

at telegram: محمد ☕️

**Comment by AlpixTM** [comment]
Hey Joe,
Looks good, he needs to contact me by mail to alpix[äät]endeavouros.com 


Lukas

**Comment by killajoe** [comment]
you can send him an email at fakeshell@bardia.tech or bardiafyt@gmail.com
bardia04@my.yorku.ca is also available ,, he says

**Comment by killajoe** [comment]
A sit was the other way around some users asked him to host a mirror..
